AWSTemplateFormatVersion: '2010-09-09'
Description: 'This CFN template creates a populated RDS MySQL instance with credentials stored in Secrets Manager. Also creates an EC2 instance with Adminer database client running on port 80. Use only in us-east-1'

Resources:
  DemoVPC:
    Type: 'AWS::EC2::VPC'
    Properties:
      CidrBlock: '10.0.0.0/16'
      EnableDnsSupport: true
      EnableDnsHostnames: true
      InstanceTenancy: 'default'
      Tags:
        - Key: 'Name'
          Value: 'demo-vpc'

  DemoSubnet:
    Type: 'AWS::EC2::Subnet'
    Properties:
      AvailabilityZone: !GetAtt DemoSubnet3.AvailabilityZone
      CidrBlock: '10.0.128.0/20'
      VpcId: !Ref DemoVPC
      MapPublicIpOnLaunch: false
      Tags:
        - Key: 'Name'
          Value: !Sub 'demo-subnet-private1-${DemoSubnet3.AvailabilityZone}'

  DemoSubnet2:
    Type: 'AWS::EC2::Subnet'
    Properties:
      AvailabilityZone: !GetAtt DemoSubnet4.AvailabilityZone
      CidrBlock: '10.0.144.0/20'
      VpcId: !Ref DemoVPC
      MapPublicIpOnLaunch: false
      Tags:
        - Key: 'Name'
          Value: !Sub 'demo-subnet-private2-${DemoSubnet4.AvailabilityZone}'

  DemoSubnet3:
    Type: 'AWS::EC2::Subnet'
    Properties:
      AvailabilityZone: !Sub '${AWS::Region}a'
      CidrBlock: '10.0.0.0/20'
      VpcId: !Ref DemoVPC
      MapPublicIpOnLaunch: true
      Tags:
        - Key: 'Name'
          Value: !Sub 'demo-subnet-public1-${AWS::Region}a'

  DemoSubnet4:
    Type: 'AWS::EC2::Subnet'
    Properties:
      AvailabilityZone: !Sub '${AWS::Region}b'
      CidrBlock: '10.0.16.0/20'
      VpcId: !Ref DemoVPC
      MapPublicIpOnLaunch: true
      Tags:
        - Key: 'Name'
          Value: !Sub 'demo-subnet-public2-${AWS::Region}b'

  DemoIG:
    Type: 'AWS::EC2::InternetGateway'
    Properties:
      Tags:
        - Key: 'Name'
          Value: 'demo-igw'

  DemoGatewayAttachment:
    Type: 'AWS::EC2::VPCGatewayAttachment'
    Properties:
      InternetGatewayId: !Ref DemoIG
      VpcId: !Ref DemoVPC

  DemoRouteTable:
    Type: 'AWS::EC2::RouteTable'
    Properties:
      VpcId: !Ref DemoVPC
      Tags:
        - Key: 'Name'
          Value: !Sub 'demo-rtb-private'

  DemoRouteTable2:
    Type: 'AWS::EC2::RouteTable'
    Properties:
      VpcId: !Ref DemoVPC
      Tags:
        - Key: 'Name'
          Value: 'demo-rtb-public'

  DemoRoute:
    Type: 'AWS::EC2::Route'
    Properties:
      DestinationCidrBlock: '0.0.0.0/0'
      GatewayId: !Ref DemoIG
      RouteTableId: !Ref DemoRouteTable2

  DemoSubnetRouteTableAssociation:
    Type: 'AWS::EC2::SubnetRouteTableAssociation'
    Properties:
      RouteTableId: !Ref DemoRouteTable
      SubnetId: !Ref DemoSubnet

  DemoSubnetRouteTableAssociation2:
    Type: 'AWS::EC2::SubnetRouteTableAssociation'
    Properties:
      RouteTableId: !Ref DemoRouteTable
      SubnetId: !Ref DemoSubnet2

  DemoSubnetRouteTableAssociation3:
    Type: 'AWS::EC2::SubnetRouteTableAssociation'
    Properties:
      RouteTableId: !Ref DemoRouteTable2
      SubnetId: !Ref DemoSubnet3

  DemoSubnetRouteTableAssociation4:
    Type: 'AWS::EC2::SubnetRouteTableAssociation'
    Properties:
      RouteTableId: !Ref DemoRouteTable2
      SubnetId: !Ref DemoSubnet4

  DemoSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: 'mysql access'
      GroupName: 'rds-sg'
      VpcId: !Ref DemoVPC
      SecurityGroupIngress:
        - SourceSecurityGroupId: !Ref DemoSecurityGroup2
          SourceSecurityGroupOwnerId: !Ref AWS::AccountId
          FromPort: 3306
          IpProtocol: 'tcp'
          ToPort: 3306
      SecurityGroupEgress:
        - CidrIp: '0.0.0.0/0'
          IpProtocol: '-1'

  DemoSecurityGroup2:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: 'db client access'
      GroupName: 'ec2-sg'
      VpcId: !Ref DemoVPC
      SecurityGroupIngress:
        - CidrIp: '0.0.0.0/0'
          FromPort: 80
          IpProtocol: 'tcp'
          ToPort: 80
        - CidrIp: '0.0.0.0/0'
          FromPort: 22
          IpProtocol: 'tcp'
          ToPort: 22
      SecurityGroupEgress:
        - CidrIp: '0.0.0.0/0'
          IpProtocol: '-1'

  DemoSecretsManager:
    Type: 'AWS::SecretsManager::Secret'
    Properties:
      Description: AWS RDS admin credentials
      Name: demo/mysql
      GenerateSecretString:
        SecretStringTemplate: '{"username": "admin"}'
        GenerateStringKey: password
        PasswordLength: 32
        ExcludeCharacters: '"@/\'

  DemoRDS:
    Type: 'AWS::RDS::DBInstance'
    Properties:
      AllocatedStorage: 20
      StorageType: gp2
      DBInstanceClass: db.t3.micro
      DBInstanceIdentifier: DemoDB
      Engine: mysql
      EngineVersion: 8.0.32
      DBSubnetGroupName: !Ref DemoDBSubnetGroup
      MasterUsername: !Sub '{{resolve:secretsmanager:${DemoSecretsManager}::username}}'
      MasterUserPassword: !Sub '{{resolve:secretsmanager:${DemoSecretsManager}::password}}'
      BackupRetentionPeriod: 7
      VPCSecurityGroups:
        - !GetAtt DemoSecurityGroup.GroupId

  DemoDBSubnetGroup:
    Type: 'AWS::RDS::DBSubnetGroup'
    Properties:
      DBSubnetGroupDescription: Demo Subnet Group
      SubnetIds:
        - !Ref DemoSubnet
        - !Ref DemoSubnet2
      Tags:
        - Key: 'Name'
          Value: !Sub 'DemoDBSubnetGroup'

  DemoSecretAttachment:
    Type: 'AWS::SecretsManager::SecretTargetAttachment'
    Properties:
      SecretId: !Ref DemoSecretsManager
      TargetId: !Ref DemoRDS
      TargetType: 'AWS::RDS::DBInstance'
    DependsOn: DemoRDS
    
  DemoKeyPair:
    Type: 'AWS::EC2::KeyPair'
    Properties:
      KeyName: DemoKeyPair

  DemoIAMRole:
    Type: "AWS::IAM::Role"
    Properties:
      Path: "/"
      RoleName: "DemoRoleSecrets"
      AssumeRolePolicyDocument: "{\"Version\":\"2012-10-17\",\"Statement\":[{\"Effect\":\"Allow\",\"Principal\":{\"Service\":\"ec2.amazonaws.com\"},\"Action\":\"sts:AssumeRole\"}]}"
      MaxSessionDuration: 3600
      ManagedPolicyArns: 
        - "arn:aws:iam::aws:policy/SecretsManagerReadWrite"
      Description: "Allows EC2 instances to call AWS services on your behalf."

  DemoInstanceProfile:
    Type: "AWS::IAM::InstanceProfile"
    Properties:
      Path: "/"
      InstanceProfileName: !Ref DemoIAMRole
      Roles: 
        - !Ref DemoIAMRole
  
  DemoEC2Instance:
    Type: 'AWS::EC2::Instance'
    Properties:
      ImageId: 'ami-090fa75af13c156b4'
      KeyName: !Ref DemoKeyPair
      InstanceType: 't3.large'
      SubnetId: !Ref DemoSubnet3
      SecurityGroupIds:
        - !Ref DemoSecurityGroup2
      UserData: 'IyEvYmluL2Jhc2gKeXVtIHVwZGF0ZSAteQp5dW0gaW5zdGFsbCAteSBkb2NrZXIKc2VydmljZSBkb2NrZXIgc3RhcnQKZG9ja2VyIHJ1biAtLW5hbWUgYWRtaW5lcjEgLWQgLXAgODA6ODA4MCBhZG1pbmVyCmN1cmwgImh0dHBzOi8vYXdzY2xpLmFtYXpvbmF3cy5jb20vYXdzY2xpLWV4ZS1saW51eC14ODZfNjQuemlwIiAtbyAiYXdzY2xpdjIuemlwIgp1bnppcCBhd3NjbGl2Mi56aXAKc3VkbyAuL2F3cy9pbnN0YWxsCnl1bSBpbnN0YWxsIC15IGpxCnl1bSBpbnN0YWxsIC15IG15c3FsCm1rZGlyIGRiLWRhdGEKY2QgZGItZGF0YQp3Z2V0IGh0dHBzOi8vcmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbS9hd3Mtc2FtcGxlcy9hbWF6b24tYXVyb3JhLW15c3FsLXNhbXBsZS1oci1zY2hlbWEvbWFzdGVyL2hyLXNjaGVtYS5zcWwKdG91Y2ggb3B0aW9ucy5pbmkKY2htb2QgNjAwIG9wdGlvbnMuaW5pCmNhdCA8PCBFT0YgPiBvcHRpb25zLmluaQpbY2xpZW50XQpob3N0ID0gJChhd3Mgc2VjcmV0c21hbmFnZXIgZ2V0LXNlY3JldC12YWx1ZSAtLXJlZ2lvbiB1cy1lYXN0LTEgLS1zZWNyZXQtaWQgZGVtby9teXNxbCAgLS1xdWVyeSAnU2VjcmV0U3RyaW5nJyAtLW91dHB1dCB0ZXh0IHwganEgLmhvc3QgfCB0ciAtZCAnIicpCnVzZXIgPSAkKGF3cyBzZWNyZXRzbWFuYWdlciBnZXQtc2VjcmV0LXZhbHVlIC0tcmVnaW9uIHVzLWVhc3QtMSAtLXNlY3JldC1pZCBkZW1vL215c3FsICAtLXF1ZXJ5ICdTZWNyZXRTdHJpbmcnIC0tb3V0cHV0IHRleHQgfCBqcSAudXNlcm5hbWUgfCB0ciAtZCAnIicpCnBhc3N3b3JkID0gJChhd3Mgc2VjcmV0c21hbmFnZXIgZ2V0LXNlY3JldC12YWx1ZSAtLXJlZ2lvbiB1cy1lYXN0LTEgLS1zZWNyZXQtaWQgZGVtby9teXNxbCAgLS1xdWVyeSAnU2VjcmV0U3RyaW5nJyAtLW91dHB1dCB0ZXh0IHwganEgLnBhc3N3b3JkIHwgdHIgLWQgJyInKQpFT0YKbXlzcWwgLS1kZWZhdWx0cy1maWxlPW9wdGlvbnMuaW5pIDwgaHItc2NoZW1hLnNxbApybSAtZiBvcHRpb25zLmluaQ=='
      IamInstanceProfile: !Ref DemoInstanceProfile
      Tags:
        - Key: 'Name'
          Value: demoDbClient
    DependsOn: DemoSecretAttachment
